"""Initial migration.

Revision ID: 947e1adc8e22
Revises: 
Create Date: 2024-10-11 15:23:17.293027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947e1adc8e22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('email_address', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=15), nullable=False))
        batch_op.add_column(sa.Column('time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('gas_data', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.drop_column('gas_data')
        batch_op.drop_column('time')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('email_address')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
